# Generated by jeweler
# DO NOT EDIT THIS FILE
# Instead, edit Jeweler::Tasks in Rakefile, and run `rake gemspec`
# -*- encoding: utf-8 -*-

Gem::Specification.new do |s|
  s.name = %q{simple-pages}
  s.version = "0.1.0"

  s.required_rubygems_version = Gem::Requirement.new(">= 0") if s.respond_to? :required_rubygems_version=
  s.authors = ["Andi Schacke"]
  s.date = %q{2010-03-21}
  s.description = %q{simple-pages is a ruby library to easily render static pages in your Ruby on Rails application.}
  s.email = %q{andreas.schacke@gmail.com}
  s.files = [
    "Rakefile",
     "VERSION",
     "generators/simple_pages/simple_pages_generator.rb",
     "generators/simple_pages/templates/simple_pages_controller.rb",
     "lib/simple-pages.rb",
     "lib/simple_pages/controller_methods.rb",
     "spec/lib/simple-pages_spec.rb",
     "spec/lib/simple_pages/controller_methods_spec.rb",
     "spec/spec_helper.rb"
  ]
  s.homepage = %q{http://github.com/andi/simple-navigation}
  s.rdoc_options = ["--inline-source", "--charset=UTF-8"]
  s.require_paths = ["lib"]
  s.rubygems_version = %q{1.3.5}
  s.summary = %q{simple-pages is a ruby library to easily render static pages in your Ruby on Rails application.}
  s.test_files = [
    "spec/lib/simple-pages_spec.rb",
     "spec/lib/simple_pages/controller_methods_spec.rb",
     "spec/spec_helper.rb"
  ]

  if s.respond_to? :specification_version then
    current_version = Gem::Specification::CURRENT_SPECIFICATION_VERSION
    s.specification_version = 3

    if Gem::Version.new(Gem::RubyGemsVersion) >= Gem::Version.new('1.2.0') then
      s.add_development_dependency(%q<rspec>, [">= 1.2.8"])
    else
      s.add_dependency(%q<rspec>, [">= 1.2.8"])
    end
  else
    s.add_dependency(%q<rspec>, [">= 1.2.8"])
  end
end
